FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install curl for healthchecks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies using uv
RUN uv sync

# Add virtual environment to PATH
ENV PATH="/app/.venv/bin:${PATH}"

# Expose port for Prefect (if running server/agent with API)
EXPOSE 4200

# Run Prefect worker&agent
#CMD ["uv", "run", "prefect", "server", "start", "--host", "0.0.0.0"]
#CMD ["uv", "run", "python", "app/flows/main_pipe.py"]
#CMD ["sh", "-c", "uv run prefect server start --host 0.0.0.0 & uv run prefect worker start --pool default-agent-pool"]