FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies using uv
RUN uv sync

# Add virtual environment to PATH
ENV PATH="/app/.venv/bin:${PATH}"

# Expose port for Prefect (if running server/agent with API)
EXPOSE 5000

# Run Prefect worker/agent
CMD ["uv", "run", "gunicorn", "--config", "gunicorn_config.py", "app.webhook:app"]