CREATE TABLE IF NOT EXISTS lnd.transactions_webhook (
    feedItemUid VARCHAR PRIMARY KEY,
    categoryUid VARCHAR NOT NULL,
    accountUid VARCHAR NOT NULL,
    amount_currency VARCHAR NOT NULL,
    amount_minorUnits INTEGER NOT NULL,
    sourceAmount_currency VARCHAR NOT NULL,
    sourceAmount_minorUnits INTEGER NOT NULL,
    direction VARCHAR NOT NULL,
    updatedAt TIMESTAMP NOT NULL,
    transactionTime TIMESTAMP NOT NULL,
    settlementTime TIMESTAMP NOT NULL,
    source VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    transactingApplicationUserUid VARCHAR NOT NULL,
    counterPartyType VARCHAR NOT NULL,
    counterPartyUid VARCHAR NOT NULL,
    counterPartyName VARCHAR NOT NULL,
    counterPartySubEntityUid VARCHAR,
    counterPartySubEntityName VARCHAR,
    counterPartySubEntityIdentifier VARCHAR,
    counterPartySubEntitySubIdentifier VARCHAR,
    exchangeRate DOUBLE,
    totalFeeAmount_currency VARCHAR,
    totalFeeAmount_minorUnits INTEGER,
    reference VARCHAR,
    country VARCHAR,
    spendingCategory VARCHAR,
    userNote VARCHAR,
    roundUp_goalCategoryUid VARCHAR,
    roundUp_amount_currency VARCHAR,
    roundUp_amount_minorUnits INTEGER,
    hasAttachment BOOLEAN NOT NULL,
    receiptPresent BOOLEAN NOT NULL,
    feedItemFailureReason VARCHAR,
    sourceUid VARCHAR ,
    webhookEventUid VARCHAR NOT NULL,
    eventTimestamp TIMESTAMP NOT NULL,
    accountHolderUid VARCHAR NOT NULL,
    last_modified TIMESTAMP,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);