CREATE TABLE IF NOT EXISTS lnd.transactions_webhook (
    feedItemUid VARCHAR PRIMARY KEY,
    categoryUid VARCHAR ,
    accountUid VARCHAR ,
    amount_currency VARCHAR ,
    amount_minorUnits INTEGER ,
    sourceAmount_currency VARCHAR ,
    sourceAmount_minorUnits INTEGER ,
    direction VARCHAR ,
    updatedAt TIMESTAMP ,
    transactionTime TIMESTAMP ,
    settlementTime TIMESTAMP ,
    source VARCHAR ,
    status VARCHAR ,
    transactingApplicationUserUid VARCHAR ,
    counterPartyType VARCHAR ,
    counterPartyUid VARCHAR ,
    counterPartyName VARCHAR ,
    counterPartySubEntityUid VARCHAR,
    counterPartySubEntityName VARCHAR,
    counterPartySubEntityIdentifier VARCHAR,
    counterPartySubEntitySubIdentifier VARCHAR,
    exchangeRate DOUBLE,
    totalFeeAmount_currency VARCHAR,
    totalFeeAmount_minorUnits INTEGER,
    reference VARCHAR,
    country VARCHAR,
    spendingCategory VARCHAR,
    userNote VARCHAR,
    roundUp_goalCategoryUid VARCHAR,
    roundUp_amount_currency VARCHAR,
    roundUp_amount_minorUnits INTEGER,
    hasAttachment BOOLEAN ,
    receiptPresent BOOLEAN ,
    feedItemFailureReason VARCHAR,
    sourceUid VARCHAR ,
    webhookEventUid VARCHAR ,
    eventTimestamp TIMESTAMP ,
    accountHolderUid VARCHAR ,
    last_modified TIMESTAMP,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);