CREATE TABLE IF NOT EXISTS lnd.transactions_api_pull
    (
      feedItemUid VARCHAR,
      categoryUid VARCHAR,
      direction VARCHAR,
      updatedAt VARCHAR,
      transactionTime VARCHAR,
      settlementTime VARCHAR,
      source VARCHAR,
      sourceSubType VARCHAR,
      status VARCHAR,
      transactingApplicationUserUid VARCHAR,
      counterPartyType VARCHAR,
      counterPartyUid VARCHAR,
      counterPartyName VARCHAR,
      counterPartySubEntityUid VARCHAR,
      reference VARCHAR,
      country VARCHAR,
      spendingCategory VARCHAR,
      userNote VARCHAR,
      hasAttachment BOOLEAN,
      hasReceipt BOOLEAN,
      batchPaymentDetails VARCHAR,
      "amount.currency" VARCHAR,
      "amount.minorUnits" BIGINT,
      "sourceAmount.currency" VARCHAR,
      "sourceAmount.minorUnits" BIGINT,
      counterPartySubEntityName VARCHAR,
      counterPartySubEntityIdentifier VARCHAR,
      counterPartySubEntitySubIdentifier VARCHAR,
      received_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );